name: Deploy Record Store

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        shell: bash

      - run: npm run build
        shell: bash
      # TODO: do I need env and tokens here?

      - run: git config user.name github-actions
        shell: bash

      - run: git config user.email github-actions@github.com
        shell: bash

      - run: git --work-tree docs add --all
        shell: bash

      - run: git commit -m "Automatic Build and Deploy run by GitHub Actions"
        shell: bash

      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git push origin HEAD:gh-pages --force
        shell: bash
